### ISSUE TITLE
Compatibility with Kotest v5.x

### ISSUE THREAD

**Issue by abendt** [kotest/kotest-extensions-testcontainers#3]
It seems that the latest version of this extension is not full compatible with latest Kotest v5.x. I get this exception when trying to migrate an existing test that uses a docker container to use the latest Kotest version

```
 java.lang.IncompatibleClassChangeError: Found interface io.kotest.core.test.TestResult, but class was expected
            at io.kotest.extensions.testcontainers.TestLifecycleAwareListener.afterTest(TestLifecycleAwareListener.kt:20)
            at io.kotest.extensions.testcontainers.StartablePerTestListener$afterTest$2.invokeSuspend(StartablePerTestListener.kt:34)
```

**Comment by sksamuel** [comment]
We'll release a compatible version in the next couple of days.

**Comment by sksamuel** [comment]
Sorry meant to come back - 1.1.0 is out with has 5.0 compatibility.
